version: '3.1'
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /D/workspace/indietour/ssl:/etc/ssl

  frontend:
    image: indietour-frontend-dev
    env_file:
      - .env
    restart: always

  
