version: '3.1'
services:
  nginx:
    image: indietour-nginx
    ports:
      - 80:80
      - 443:443

  frontend:
    image: indietour-frontend-dev
    env_file:
      - .env
    restart: always

  
