version: '3.1'
services:
  # frontend:
  #   image: dstoffels/indietour-frontend:latest
  #   env_file:
  #     - .env
  #   ports:
  #     - 80:8000
  #   depends_on:
  #     - db
  #   restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - /certbot/certs:/etc/nginx/certs
