version: '3.1'
services:
  frontend:
    build: ./
    image: indietour-frontend-dev
    env_file:
      - .env
    restart: always

  nginx:
    build: ./nginx
    image: indietour-nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend
    volumes:
      - /D/workspace/indietour/ssl:/etc/ssl

  
