version: '3.1'
services:
  frontend:
    image: dstoffels/indietour-frontend:latest
    env_file:
      - .env
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - webroot:/var/www/certbot
      - ssl-certs:/etc/letsencrypt

  certbot:
    image: certbot/certbot
    volumes:
      - webroot:/var/www/certbot
      - ssl-certs:/etc/letsencrypt
    command: echo
    depends_on:
      - nginx

volumes:
  ssl-certs:
    driver: local
    driver_opts:
      type: none
      device: /etc/letsencrypt
      o: bind
  webroot:
    driver: local
    driver_opts:
      type: none
      device: /var/www/certbot
      o: bind
